# Generated by Django 5.0.7 on 2024-07-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد فعال سازی ایمیل'),
        ),
    ]
