# Generated by Django 5.0.7 on 2024-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_about_us', models.CharField(max_length=300, verbose_name='عنوان صفحه درباره ما')),
                ('text_about_us', models.TextField(verbose_name='متن صفحه درباره ما')),
                ('image_about_us', models.ImageField(upload_to='about_us', verbose_name='تصویر صفجه درباره ما')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن مزایای کلینیک')),
                ('image_1', models.ImageField(upload_to='about_us', verbose_name='تصویر اول')),
                ('image_2', models.ImageField(upload_to='about_us', verbose_name='تصویر دوم')),
            ],
            options={
                'verbose_name': 'مزیت',
                'verbose_name_plural': 'مزایا',
            },
        ),
        migrations.CreateModel(
            name='GrowthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4, verbose_name='سال وقوع اتفاق')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اتفاق')),
                ('text', models.TextField(verbose_name='متن اتفاق')),
                ('image', models.ImageField(upload_to='history', verbose_name='تصویر اتفاق')),
            ],
            options={
                'verbose_name': 'تاریخچه رشد',
                'verbose_name_plural': 'تاریخچه های رشد',
            },
        ),
        migrations.CreateModel(
            name='HappyCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('comment', models.TextField(verbose_name='نظر مشتری')),
                ('city', models.CharField(max_length=100, verbose_name='شهر مشتری')),
            ],
            options={
                'verbose_name': 'مشتری خوشحال',
                'verbose_name_plural': 'مشتریان حوشحال',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال متدوال')),
                ('answer', models.TextField(verbose_name='پاسخ سوال متدوال')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
    ]
