# Generated by Django 5.0.7 on 2024-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthhistory',
            name='year',
            field=models.IntegerField(verbose_name='سال وقوع اتفاق'),
        ),
    ]
