# Generated by Django 5.0.7 on 2024-07-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_growthhistory_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HappyCustomers',
        ),
    ]
