# Generated by Django 5.0.7 on 2024-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دکتر')),
                ('skill', models.CharField(max_length=100, verbose_name='مهارت و تخصص')),
                ('image', models.ImageField(upload_to='doctors', verbose_name='تصویر دکتر')),
                ('description', models.TextField(verbose_name='توضیخات در مورد دکتر')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل دکتر')),
                ('office_phone', models.IntegerField(max_length=11, verbose_name='شماره مطب دکتر')),
                ('history', models.IntegerField(verbose_name='سابقه دکتر /چند سال')),
            ],
            options={
                'verbose_name': 'دکتر',
                'verbose_name_plural': 'دکتر ها',
            },
        ),
    ]
