# Generated by Django 5.0.7 on 2024-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='office_phone',
            field=models.IntegerField(verbose_name='شماره مطب دکتر'),
        ),
    ]
