# Generated by Django 5.0.7 on 2024-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_doctor_office_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'پزشک', 'verbose_name_plural': 'پزشکان'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(verbose_name='توضیخات در مورد پزشک'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل پزشک'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='history',
            field=models.IntegerField(verbose_name='سابقه پزشک /چند سال'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(upload_to='doctors', verbose_name='تصویر پزشک'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام پزشک'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='office_phone',
            field=models.CharField(max_length=11, verbose_name='شماره مطب پزشک'),
        ),
    ]
