# Generated by Django 5.0.7 on 2024-07-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
