# Generated by Django 5.0.7 on 2024-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان سرویس')),
                ('short_description', models.CharField(max_length=400, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('image', models.ImageField(upload_to='services', verbose_name='تصویر سرویس')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
    ]
