# Generated by Django 5.0.7 on 2024-07-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین'),
        ),
    ]
