# Generated by Django 5.0.7 on 2024-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('phone', models.IntegerField(max_length=11, verbose_name='شماره تماس')),
                ('message', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'فرم تماس با ما',
                'verbose_name_plural': 'فرم های تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('phone_1', models.IntegerField(max_length=11, verbose_name='تلفن 1')),
                ('phone_2', models.IntegerField(blank=True, max_length=11, null=True, verbose_name='تلفن 2(اختیاری)')),
                ('email_1', models.EmailField(max_length=254, verbose_name='ایمیل 1')),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل 2(اختیاری)')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
    ]
