# Generated by Django 5.0.7 on 2024-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.IntegerField(verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_1',
            field=models.IntegerField(verbose_name='تلفن 1'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='تلفن 2(اختیاری)'),
        ),
    ]
