# Generated by Django 5.0.7 on 2024-07-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contactform_phone_alter_contactus_phone_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_1',
            field=models.CharField(max_length=11, verbose_name='تلفن 1'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_2',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن 2(اختیاری)'),
        ),
    ]
