# Generated by Django 5.0.7 on 2024-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_alter_contactform_phone_alter_contactus_phone_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/نشده'),
        ),
    ]
